version: '3.8'
services:
  db:
    image: "${IMAGE}"
    environment:
      POSTGRES_USER: "${PGUSER}"
      POSTGRES_PASSWORD: "${PGPASSWORD}"
      POSTGRES_DB: "${PGDATABASE}"
    ports:
      - "${PG_PORT_MAPPING}"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL="postgresql://root:integral@db:5433/routes-db?sslmode=disable"
    volumes:
      - ./:/app
volumes:
  pgdata:
