// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: all.sql

package db

import (
	"context"
)

const getBuildingOrPlace = `-- name: GetBuildingOrPlace :one
WITH Combined AS (SELECT name, st_astext(geom) as geom
                  FROM place
                  WHERE place.name = $1

                  UNION

                  SELECT name, st_astext(st_centroid(geom)) as geom
                  FROM building
                  WHERE building.name = $1)
SELECT name, geom
FROM Combined
limit 1
`

type GetBuildingOrPlaceRow struct {
	Name string      `json:"name"`
	Geom interface{} `json:"geom"`
}

func (q *Queries) GetBuildingOrPlace(ctx context.Context, name string) (GetBuildingOrPlaceRow, error) {
	row := q.db.QueryRow(ctx, getBuildingOrPlace, name)
	var i GetBuildingOrPlaceRow
	err := row.Scan(&i.Name, &i.Geom)
	return i, err
}

const getClosestPointToQueryLocationByLatLngGeom = `-- name: GetClosestPointToQueryLocationByLatLngGeom :one
SELECT id,
       name,
       ST_ASTEXT(geom) AS closest_geom
FROM node
ORDER BY geom <-> st_transform(ST_GEOMFROMTEXT($1, 4326), 3857)
LIMIT 1
`

type GetClosestPointToQueryLocationByLatLngGeomRow struct {
	ID          int64       `json:"id"`
	Name        string      `json:"name"`
	ClosestGeom interface{} `json:"closest_geom"`
}

func (q *Queries) GetClosestPointToQueryLocationByLatLngGeom(ctx context.Context, stGeomfromtext interface{}) (GetClosestPointToQueryLocationByLatLngGeomRow, error) {
	row := q.db.QueryRow(ctx, getClosestPointToQueryLocationByLatLngGeom, stGeomfromtext)
	var i GetClosestPointToQueryLocationByLatLngGeomRow
	err := row.Scan(&i.ID, &i.Name, &i.ClosestGeom)
	return i, err
}
