// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: buildings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listBuildings = `-- name: ListBuildings :many
SELECT name, ST_ASTEXT(geom) as geom, ST_ASTEXT(geom_geography) as geom_geographic
from buildings
order by id
`

type ListBuildingsRow struct {
	Name           pgtype.Text `json:"name"`
	Geom           interface{} `json:"geom"`
	GeomGeographic interface{} `json:"geom_geographic"`
}

func (q *Queries) ListBuildings(ctx context.Context) ([]ListBuildingsRow, error) {
	rows, err := q.db.Query(ctx, listBuildings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBuildingsRow{}
	for rows.Next() {
		var i ListBuildingsRow
		if err := rows.Scan(&i.Name, &i.Geom, &i.GeomGeographic); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
