// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: building.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBuildingCentroidGeom = `-- name: GetBuildingCentroidGeom :one
SELECT ST_ASTEXT(centroid)           as building_centroid,
       ST_ASTEXT(centroid_geography) as building_centroid_geographic
from buildings
where name = $1
`

type GetBuildingCentroidGeomRow struct {
	BuildingCentroid           interface{} `json:"building_centroid"`
	BuildingCentroidGeographic interface{} `json:"building_centroid_geographic"`
}

func (q *Queries) GetBuildingCentroidGeom(ctx context.Context, name pgtype.Text) (GetBuildingCentroidGeomRow, error) {
	row := q.db.QueryRow(ctx, getBuildingCentroidGeom, name)
	var i GetBuildingCentroidGeomRow
	err := row.Scan(&i.BuildingCentroid, &i.BuildingCentroidGeographic)
	return i, err
}

const listBuildings = `-- name: ListBuildings :many
SELECT name,
       ST_ASTEXT(geom)           as geom,
       ST_ASTEXT(geom_geography) as geom_geographic
from buildings
order by id
`

type ListBuildingsRow struct {
	Name           pgtype.Text `json:"name"`
	Geom           interface{} `json:"geom"`
	GeomGeographic interface{} `json:"geom_geographic"`
}

func (q *Queries) ListBuildings(ctx context.Context) ([]ListBuildingsRow, error) {
	rows, err := q.db.Query(ctx, listBuildings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBuildingsRow{}
	for rows.Next() {
		var i ListBuildingsRow
		if err := rows.Scan(&i.Name, &i.Geom, &i.GeomGeographic); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
