// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/twpayne/go-geom"
)

type Building struct {
	ID         int64       `json:"id"`
	Name       string      `json:"name"`
	Geom       geom.Point  `json:"geom"`
	CategoryID pgtype.Int4 `json:"category_id"`
	ImageUrls  []string    `json:"image_urls"`
}

type Category struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Classroom struct {
	ID          int64       `json:"id"`
	BuildingID  int64       `json:"building_id"`
	RoomCode    string      `json:"room_code"`
	CategoryID  pgtype.Int4 `json:"category_id"`
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
	ImageUrls   []string    `json:"image_urls"`
}

type Edge struct {
	ID         int64   `json:"id"`
	FromNodeID int64   `json:"from_node_id"`
	ToNodeID   int64   `json:"to_node_id"`
	Weight     float64 `json:"weight"`
}

type Node struct {
	ID   int64      `json:"id"`
	Name string     `json:"name"`
	Geom geom.Point `json:"geom"`
}

type Place struct {
	ID         int64       `json:"id"`
	Name       string      `json:"name"`
	Geom       geom.Point  `json:"geom"`
	CategoryID pgtype.Int4 `json:"category_id"`
}
