// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: place.sql

package db

import (
	"context"
)

const getPlace = `-- name: GetPlace :one
SELECT name,
       ST_ASTEXT(geom)                     as geom,
       ST_ASTEXT(ST_TRANSFORM(geom, 4326)) as geom_geographic
from place
where name = $1
`

type GetPlaceRow struct {
	Name           string      `json:"name"`
	Geom           interface{} `json:"geom"`
	GeomGeographic interface{} `json:"geom_geographic"`
}

func (q *Queries) GetPlace(ctx context.Context, name string) (GetPlaceRow, error) {
	row := q.db.QueryRow(ctx, getPlace, name)
	var i GetPlaceRow
	err := row.Scan(&i.Name, &i.Geom, &i.GeomGeographic)
	return i, err
}

const getPlaceByNameOrGeom = `-- name: GetPlaceByNameOrGeom :one
select name            as placeName,
       st_astext(geom) as PlaceGeom
from place
where place.name = $1
   or place.geom = (select geom as Geom
                    from place
                    order by geom <-> st_geomfromtext($2, 3857)
                    limit 1)
`

type GetPlaceByNameOrGeomParams struct {
	Name           string      `json:"name"`
	StGeomfromtext interface{} `json:"st_geomfromtext"`
}

type GetPlaceByNameOrGeomRow struct {
	Placename string      `json:"placename"`
	Placegeom interface{} `json:"placegeom"`
}

func (q *Queries) GetPlaceByNameOrGeom(ctx context.Context, arg GetPlaceByNameOrGeomParams) (GetPlaceByNameOrGeomRow, error) {
	row := q.db.QueryRow(ctx, getPlaceByNameOrGeom, arg.Name, arg.StGeomfromtext)
	var i GetPlaceByNameOrGeomRow
	err := row.Scan(&i.Placename, &i.Placegeom)
	return i, err
}

const getPlaceGeom = `-- name: GetPlaceGeom :one
SELECT ST_ASTEXT(geom)                     as geom,
       ST_ASTEXT(ST_TRANSFORM(geom, 4326)) as geom_geographic
from place
where name = $1
`

type GetPlaceGeomRow struct {
	Geom           interface{} `json:"geom"`
	GeomGeographic interface{} `json:"geom_geographic"`
}

func (q *Queries) GetPlaceGeom(ctx context.Context, name string) (GetPlaceGeomRow, error) {
	row := q.db.QueryRow(ctx, getPlaceGeom, name)
	var i GetPlaceGeomRow
	err := row.Scan(&i.Geom, &i.GeomGeographic)
	return i, err
}

const listPlaces = `-- name: ListPlaces :many
SELECT name
     , ST_ASTEXT(geom)                     as geom
     , ST_ASTEXT(ST_TRANSFORM(geom, 4326)) as geom_geographic
from place
order by id
`

type ListPlacesRow struct {
	Name           string      `json:"name"`
	Geom           interface{} `json:"geom"`
	GeomGeographic interface{} `json:"geom_geographic"`
}

func (q *Queries) ListPlaces(ctx context.Context) ([]ListPlacesRow, error) {
	rows, err := q.db.Query(ctx, listPlaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlacesRow{}
	for rows.Next() {
		var i ListPlacesRow
		if err := rows.Scan(&i.Name, &i.Geom, &i.GeomGeographic); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
