// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: place.sql

package db

import (
	"context"
)

const getPlace = `-- name: GetPlace :one
SELECT name,
       ST_ASTEXT(location)                     as location,
       ST_ASTEXT(ST_TRANSFORM(location, 4326)) as location_geographic
from place
where name = $1
`

type GetPlaceRow struct {
	Name               string      `json:"name"`
	Location           interface{} `json:"location"`
	LocationGeographic interface{} `json:"location_geographic"`
}

func (q *Queries) GetPlace(ctx context.Context, name string) (GetPlaceRow, error) {
	row := q.db.QueryRow(ctx, getPlace, name)
	var i GetPlaceRow
	err := row.Scan(&i.Name, &i.Location, &i.LocationGeographic)
	return i, err
}

const getPlaceGeom = `-- name: GetPlaceGeom :one
SELECT ST_ASTEXT(location)                     as location,
       ST_ASTEXT(ST_TRANSFORM(location, 4326)) as location_geographic
from place
where name = $1
`

type GetPlaceGeomRow struct {
	Location           interface{} `json:"location"`
	LocationGeographic interface{} `json:"location_geographic"`
}

func (q *Queries) GetPlaceGeom(ctx context.Context, name string) (GetPlaceGeomRow, error) {
	row := q.db.QueryRow(ctx, getPlaceGeom, name)
	var i GetPlaceGeomRow
	err := row.Scan(&i.Location, &i.LocationGeographic)
	return i, err
}

const listPlaces = `-- name: ListPlaces :many
SELECT name
     , ST_ASTEXT(location)                     as location
     , ST_ASTEXT(ST_TRANSFORM(location, 4326)) as location_geographic
from place
order by id
`

type ListPlacesRow struct {
	Name               string      `json:"name"`
	Location           interface{} `json:"location"`
	LocationGeographic interface{} `json:"location_geographic"`
}

func (q *Queries) ListPlaces(ctx context.Context) ([]ListPlacesRow, error) {
	rows, err := q.db.Query(ctx, listPlaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlacesRow{}
	for rows.Next() {
		var i ListPlacesRow
		if err := rows.Scan(&i.Name, &i.Location, &i.LocationGeographic); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
